# Generated by Django 3.2.15 on 2022-10-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('disc', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('year', models.IntegerField()),
            ],
        ),
    ]
